version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: example
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 8001:80
  app:
    image: "node:10"
    depends_on:
    - db
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    environment:
      NODE_ENV: development
    ports:
      - 8000:80
    command: npm run dev